# Site settings
title: "Concept Home Renovation"
description: >-
  Experts in full house renovations, from kitchen remodels to entire home transformations. We bring your vision to life.
baseurl: "" # Keep this empty for GitHub Pages
url: "https://wk-cof.github.io/concept-home-renovation/" # Actual GitHub Pages URL

twitter_username: "concepthrv"

# Theme settings
remote_theme: pages-themes/slate

# Plugins
plugins:
  - jekyll-remote-theme

# Contact Information
email: "concepthrv@gmail.com"
phone: "+1 (203) 427-7968"

markdown: kramdown
